# Generated by Django 4.1.2 on 2022-10-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='shortdesc',
            field=models.CharField(default='', max_length=300),
        ),
    ]
